# Generated by Django 3.0.5 on 2020-05-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(default='https://g.foolcdn.com/editorial/images/539523/airplane-takeoff-getty.jpg', upload_to='news'),
        ),
    ]
