# Generated by Django 3.0.5 on 2020-06-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200602_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text',
        ),
        migrations.AddField(
            model_name='news',
            name='about1',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='news',
            name='about2',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='news',
            name='about3',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='news',
            name='photo1',
            field=models.TextField(null=True, verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='news',
            name='photo2',
            field=models.TextField(null=True, verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='news',
            name='photo3',
            field=models.TextField(null=True, verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='news',
            name='title1',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title2',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title3',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
    ]
