# Generated by Django 3.0.5 on 2020-06-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200603_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='about1',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='news',
            name='about2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='about3',
        ),
        migrations.RemoveField(
            model_name='news',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title3',
        ),
    ]
