# Generated by Django 3.0.5 on 2020-05-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='numIcon',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
