# Generated by Django 3.0.5 on 2020-06-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isParent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='numIcon',
        ),
    ]
