# Generated by Django 3.0.5 on 2020-05-27 07:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arival', models.CharField(max_length=50, verbose_name='arival')),
                ('departure', models.CharField(max_length=50, verbose_name='departure')),
                ('date', models.DateField(max_length=50, verbose_name='date')),
                ('child', models.BooleanField(verbose_name='child')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
